### ISSUE TITLE
How do I configure this plugin from Spyder?

### ISSUE THREAD

**Issue by Greedquest** [python-lsp/pylsp-mypy#30]
I know this is not really your concern as this plug-in is host IDE agnostic. However you might know so I thought I'd ask. From the readme:

> Depending on your editor, the configuration (found in a file called pylsp-mypy.cfg in your workspace or a parent directory) should be roughly like this for a standard configuration:

I'm more used to seeing config like this (from tomv564/pyls-mypy):
```
"pyls":
{
    "plugins":
    {
        "pyls_mypy":
        {
            "enabled": true,
            "live_mode": false
        }
    }
}
```
Which I think is how I enter config for jupyterlab's lsp. However in this fork's readme you just have a single array not some nested hierarchy:
```
{
    "enabled": True,
    "overrides": ["--python-executable", "/home/me/bin/python", True]
}
```

So how do I enter that for Spyder, any ideas?

**Comment by Greedquest** [comment]
Fwiw there's no pylsp-mypy.cfg  I can find and it doesn't help if I make one in the root folder of my project, maybe Spyder does not use the same mechanism as other ides

**Comment by Richardk2n** [comment]
Sorry for not responding to your last issue. Feel free to leave them open. If I don't respond, that does not mean I wont, that means, I haven't had time yet (And/Or no idea how to help you yet).

First things first, I use this with spyder and specifically wrote/adapted it to use it with spyder, therefore I would like to assure you, that you will get it working with spyder. Furthermore this should be IDE agnostic. Some IDEs provide neat ways to pass configs. Spyder does not (as far as I am aware please correct me otherwise), therefore we have to use config files, but other than that the only uncertainty I am not completely sure about is how the root path for the diagnostic is determined. This might also be provided by the IDE. However, this should not be an issue.

The first config option is how you would configure the server to tell the plugin which configs to use. I am reasonably sure, that this would also work with the present code given the plugin name is specified correctly. However I never figured out where I am supposed to place that config file (I would be glad if you could tell me). Therefore, I wrote a different system (giving the plugin its own config file, which is structured like the second code you posted). This config files only contains the options of this plugin therefore only the last dict in the nested hierarchy. Such a config file does not exist by default, you have to create it. If named correctly and placed in the root folder of your project or a parent directory, the plugin should find it. If it does not, I would like to ask you how your project is set up. Please be very specific about your folder structure and python environments. Also please provide a ``pip list``.

**Comment by Greedquest** [comment]
> Sorry for not responding to your last issue. Feel free to leave them open. If I don't respond, that does not mean I wont, that means, I haven't had time yet (And/Or no idea how to help you yet).
No worries, I actually closed the last issue because I felt it was less clear than opening a fresh one like this. But thanks for the reassurance :)!

Regarding this issue, I've made a bit of progress:
 - Firstly, I opened an issue over in spyder and got this response https://github.com/spyder-ide/spyder/issues/17152#issuecomment-1008084770. Essentially _"unfortunately, it's not possible for third-party plugins of the PyLSP to access or extend [the configuration] mechanism, and I can't think of an easy way to allow for that [...] Eventually, we plan to integrate that plugin in Spyder, and then we'll offer an easy way to configure it."_. So you've done the right thing making an additional config file as Spyder only supports a certain hardcoded subset of lsp plugins with its internal config mechanism.
 - Secondly, I added some print-to-file logging my local copy of `plugin.py` file (incidentally, where  does the logging you've included  - e.g. https://github.com/Richardk2n/pylsp-mypy/blob/master/pylsp_mypy/plugin.py#L72 - actually go to in Spyder?). It showed that the "workspace" dir is not the cwd displayed in the top right but the root of my Spyder project. As it happens the cfg file actually is being picked up correctly, I was on a slightly older version of this plugin where "overrides" were not fully implemented so I was confused when nothing happened.

Anyway, thanks for explaining the thought process behind the configs, I feel I've learnt enough to debug it myself now (to some extent)

**Comment by Richardk2n** [comment]
In regards to the logs:
Spyder runs the language server that in turns runs the plugins as a subprocess. If you are confident you can hook into the output of this python subprocess. Otherwise, there is also a log file in your spyder directory. On Linux it is ``~/.config/spyder-py3``, on WIndows it is in your users directory under ``.spyder-py3``
In this folder go to the folder ``lsp_logs``, the server log file is what you want.

Thanks for the information, I always assumed the root of the project the be the cwd as as far as I know, this is the usual usecase. Thanks for the heads up.

If you need additional help feel free to ask, otherwise feel free to close the issue once you have got it working.
