### ISSUE TITLE
How to install Django stubs to python-lsp-server mypy plugin

### ISSUE THREAD

**Issue by jhartum** [python-lsp/pylsp-mypy#56]
I install Django-stubs in venv but I still got mypy errors about Django
<img width="903" alt="image" src="https://user-images.githubusercontent.com/65132968/216926780-070f520e-bf66-4065-9bdb-398e9a1f4437.png">

**Comment by Richardk2n** [comment]
Related to #50 I assume?
Do not close Issues just to open new ones about the same problem!

This is not a stubs not found error. Seems like a normal mypy report in relation to your code?
(Assuming `models.py` is your code and contains these untyped parameters) this works as intended.
If this assumption is wrong please elaborate.

**Comment by jhartum** [comment]
thank you for your answer
sorry for duplicate issue, I just think it's not the same problems. In #50 issue I just trying to configure mypy installed from mason, but now I wanna use mypy as plugin to python-lsp-server
I get this error, and I found this [stackoverflow question](https://stackoverflow.com/questions/59031982/type-annotations-for-django-models) and they say install Django-stubs, so I install it in my vent but still got this errors
I think mypy just not configured to use Django-stubs, is it possible to configure mypy from pyproject.toml file?


<img width="599" alt="image" src="https://user-images.githubusercontent.com/65132968/216936169-ce32e4f6-6fc3-4e0d-80a8-1415b87d52f2.png">

**Comment by jhartum** [comment]
@Richardk2n I need to continue this issue in #50 ?

**Comment by Richardk2n** [comment]
If the issue is not related, creating a new one is fine.
pylsp-mypy is just a bridge between the python-lsp-server and mypy. As far as I can tell your issue is not with pylsp-mypy.

pylsp-mypy does some of its own handling of config files but as far as i know it supports all files/locations specified by mypy. pyproject.toml is also supported. How to configure mypy correctly for django-stubs is outside of the scope of this project (and I don't know).

**Comment by jhartum** [comment]
can i explicitly specify path to config file for pylsp-mypy?
